# Generated by Django 4.1 on 2023-02-15 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='zipcode',
            new_name='pincode',
        ),
        migrations.RenameField(
            model_name='orderplaced',
            old_name='Ordered_date',
            new_name='ordered_date',
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Maharashtra', 'Maharashtra')], max_length=50),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Packed', 'Packed'), ('On The Way', 'On The Way'), ('Delivered', 'Delivered'), ('Cancel', 'Cancel')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('d', 'Digestives'), ('hd', 'HealthDrinks'), ('fb', 'FruitBeverages'), ('hw', 'HealthWellness'), ('df', 'DietFood'), ('hp', 'OtherHealth'), ('bc', 'BiscuitsCookies'), ('s', 'Spices'), ('dp', 'DalPulses'), ('eo', 'EdibleOil'), ('su', 'Sugar'), ('fd', 'DryFruits'), ('fp', 'OtherFood'), ('k', 'Kwath'), ('o', 'Oil'), ('c', 'Churna'), ('a', 'Asava'), ('v', 'Vati'), ('g', 'Guggul'), ('ag', 'Agarbatti'), ('dh', 'Dhoop'), ('dw', 'DishWasher'), ('hm', 'HawanMaterial'), ('tc', 'ToiletCleaner'), ('wh', 'HandWash'), ('cs', 'SkinCare'), ('cb', 'BodyCare'), ('ch', 'HairCare'), ('cd', 'DentalCare'), ('ce', 'EyeCare'), ('sc', 'ShishuCare')], max_length=2),
        ),
    ]
