# Generated by Django 4.1 on 2023-02-15 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_zipcode_customer_pincode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(choices=[('Pune', 'Pune')], max_length=50),
        ),
    ]
